[package]
name = "apidoc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
linkme = "0.3"
serde = { version = "1", features = ["derive"] }
apidoc-macros = { path = "../apidoc-macros", version = "0.1.0" }

[dev-dependencies]
serde_json = "1"
apidoc-test-fixtures = { path = "../apidoc-test-fixtures", version = "0.1.0" }
